language: php
addons:
  apt:
    packages:
      - xvfb

sudo: false
matrix:
    include:
        - php: 5.6
          env: coverage=phpunit
        - php: 5.6
          env: coverage=phpspec
        - php: 7.0
        - php: 5.6
        - php: 5.5
    fast_finish: true

cache:
  directories:
    - vendor
    - bin
    - node_modules

before_script:
  - nvm install 4.1.2
  - npm install
  - sh -e /etc/init.d/xvfb start
  - export DISPLAY=:99.0

  - if [ ! -f bin/selenium.jar ]; then curl -L http://selenium-release.storage.googleapis.com/2.50/selenium-server-standalone-2.50.1.jar > bin/selenium.jar; fi
  - java -jar bin/selenium.jar > selenium.log 2>&1 &

  - cp etc/travis-ci/.coveralls.yml .coveralls.yml
  - cp etc/travis-ci/app/config/parameters.yml app/config/parameters.yml
  - cp etc/travis-ci/web/app_test.php web/app_test.php
  - if [[ $coverage == 'phpspec' ]]; then cp etc/ci/phpspec.yml phpspec.yml; fi;
  - sed -i 's/https:\/\/test.devboardxyz.loc\//http:\/\/localhost:8000\/app_test.php\//' behat.yml

  - sed -i 's/^/;/' ~/.phpenv/versions/$(phpenv global)/etc/conf.d/xdebug.ini
  - composer install --prefer-source

  - php app/console doctrine:database:create --env=test --if-not-exists
  - php app/console doctrine:migrations:migrate --env=test --no-interaction
  - php app/console doctrine:fixtures:load --env=test --no-interaction
  - sed -i 's/FAKE-GITHUB-ID-TEST/"'$GITHUB_ID'"/' app/config/parameters.yml
  - sed -i 's/FAKE-GITHUB-SECRET-TEST/"'$GITHUB_SECRET'"/' app/config/parameters.yml
  - php app/console server:start --env=test

script:
  - if [[ $coverage == 'phpunit' ]]; then sed -i 's/^;//' ~/.phpenv/versions/$(phpenv global)/etc/conf.d/xdebug.ini; fi;
  - php -d 'xdebug.max_nesting_level=500' bin/phpunit --exclude-group GitHubMutable
  - if [[ $coverage == 'phpunit' ]]; then sed -i 's/^/;/' ~/.phpenv/versions/$(phpenv global)/etc/conf.d/xdebug.ini; fi;
  - if [[ $coverage == 'phpunit' ]]; then php bin/coveralls -v; fi;
  - if [[ $coverage == 'phpspec' ]]; then sed -i 's/^;//' ~/.phpenv/versions/$(phpenv global)/etc/conf.d/xdebug.ini; fi;
  - ./bin/phpspec run --no-interaction
  - if [[ $coverage == 'phpspec' ]]; then sed -i 's/^/;/' ~/.phpenv/versions/$(phpenv global)/etc/conf.d/xdebug.ini; fi;
  - if [[ $coverage == 'phpspec' ]]; then php bin/coveralls -v; fi;
  - ./bin/behat
  - rm -rf app/cache/* app/check.php app/SymfonyRequirements.php
  - ant php-cs-fixer-check-task
  - ant phpcs-task
  - ant phpmd-task
