imports:
    - { resource: config_dev.yml }

parameters:
    database_name: devboardxyz_test
    doctrine.dbal.connection_factory.class: Liuggio\Fastest\Doctrine\DBAL\ConnectionFactory

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

# Twig Configuration
twig:
    globals:
        github_client_id: %github_client_id_test%
        github_default_scope: "user,read:org,repo"

swiftmailer:
    disable_delivery: true
hwi_oauth:
    # name of the firewall in which this bundle is active, this setting MUST be set
    firewall_name: main
    resource_owners:
        github:
            type:                github
            client_id:           %github_client_id_test%
            client_secret:       %github_client_secret_test%