imports:
    - { resource: config.yml }

#framework:
#    validation:
#        cache: validator.mapping.cache.apc
#    serializer:
#        cache: serializer.mapping.cache.apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    channels: ["ghnotifictation"]
    handlers:
        mail:
            type:         fingers_crossed
            # 500 errors are logged at the critical level
            action_level: error
            handler:      buffered
        buffered:
            type:    buffer
            handler: swift
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type:  console
        ghnotifictationlog:
            type: stream
            path: "%kernel.logs_dir%/gh-notification.log"
            level: info
            channels: [ghnotifictation]
        swift:
            type:       swift_mailer
            from_email: error@devboard.xyz
            to_email:   miro+devboarderr@mirosvrtan.me
            subject:    An Error Occurred!
            level:      debug