DevBoard\Github\Commit\Entity\GithubCommit:
  type: entity
  table: GithubCommits
  repositoryClass: DevBoard\Github\Commit\Entity\GithubCommitRepository
  id:
    id:
      type: guid
      id: true
      generator:
        strategy: UUID
  fields:
    sha:
      type: string
      length: '255'
    authorDate:
      type: datetime
    committerDate:
      type: datetime
    message:
      type: string
      length: '255'
    internalStatus:
      type: integer
      nullable: true
    githubStatus:
      type: integer
      nullable: true
    createdAt:
      type: datetime
    updatedAt:
      type: datetime
  uniqueConstraints:
    uniq_repo_sha:
      columns: ["githubRepoId", "sha"]
  manyToOne:
    githubRepo:
      targetEntity: DevBoard\Github\Repo\Entity\GithubRepo
      joinColumn:
        name: githubRepoId
        referencedColumnName: id
    author:
      targetEntity: DevBoard\Github\User\Entity\GithubUser
      cascade: ["persist"]
      joinColumn:
        name: authorId
        referencedColumnName: id
    committer:
      targetEntity: DevBoard\Github\User\Entity\GithubUser
      cascade: ["persist"]
      joinColumn:
        name: committerId
        referencedColumnName: id
  oneToMany:
    commitStatuses:
      targetEntity: DevBoard\Github\CommitStatus\Entity\GithubCommitStatus
      mappedBy: githubCommit
    branches:
      targetEntity: DevBoard\Github\Branch\Entity\GithubBranch
      mappedBy: lastCommit
  lifecycleCallbacks:
    prePersist: ['doCreatedValue']
    preUpdate: ['doUpdatedValue']
