imports:
  - { resource: payload.yml }
  - { resource: push.yml }
  - { resource: pull_request.yml }
  - { resource: status.yml }
services:

  github.event.handler:
    class: DevBoard\GithubEvent\EventHandler
    arguments:
      - @github.event.payload.factory
      - @github.event.push.handler
      - @github.event.status.handler
      - @github.event.pull_request.handler
