services:

  github.event.pull_request.handler:
    class: DevBoard\GithubEvent\PullRequest\PullRequestHandler
    arguments:
      - @github.event.pull_request.data.repo.factory
      - @github.event.pull_request.data.pull_request.factory
      - @github.event.pull_request.data.commit.factory
      - @github.event.pull_request.data.pull_request_creator.factory
      - @github.event.pull_request.data.pull_request_assignee.factory
      - @github.repo.facade
      - @github.pull_request.facade
      - @github.commit.facade
      - @github.user.facade
      - @doctrine.orm.entity_manager

  github.event.pull_request.data.repo.factory:
    class: DevBoard\GithubEvent\PullRequest\Data\RepoFactory

  github.event.pull_request.data.pull_request.factory:
    class: DevBoard\GithubEvent\PullRequest\Data\PullRequestFactory

  github.event.pull_request.data.commit.factory:
    class: DevBoard\GithubEvent\PullRequest\Data\CommitFactory

  github.event.pull_request.data.pull_request_creator.factory:
    class: DevBoard\GithubEvent\PullRequest\Data\PullRequestCreatorFactory

  github.event.pull_request.data.pull_request_assignee.factory:
    class: DevBoard\GithubEvent\PullRequest\Data\PullRequestAssigneeFactory

