dev_board_core_project:
    resource: "@DevBoardCoreBundle/Resources/config/routing/project.yml"
    prefix:   /project

dev_board_core_homepage:
    path:     /hello/{name}
    defaults: { _controller: DevBoardCoreBundle:Default:index }
