dev_board_core_project:
    resource: "@DevBoardCoreBundle/Resources/config/routing/project.yml"
    prefix:   /project

dashboard:
    path:     /dashboard/
    defaults: { _controller: DevBoardCoreBundle:Dashboard:index }
dashboard_livebranches:
    path:     /dashboard/livebranches
    defaults: { _controller: DevBoardCoreBundle:Dashboard:livebranches }
