dev_board_core_project:
    resource: "@DevBoardCoreBundle/Resources/config/routing/project.yml"
    prefix:   /project

dashboard:
    path:     /dashboard/
    defaults: { _controller: DevBoardCoreBundle:Default:index }
