null_dev_user_homepage:
    path:     /hello/{name}
    defaults: { _controller: NullDevUserBundle:Default:index }

null_dev_user_connect_github:
    path:     /connect/github
    defaults: { _controller: NullDevUserBundle:Connect:github }