hwi_oauth:
    # name of the firewall in which this bundle is active, this setting MUST be set
    firewall_names: [main]
    resource_owners:
        github:
            type:                github
            client_id:           %github_client_id%
            client_secret:       %github_client_secret%