imports:
  - { resource: services/repo.yml }
  - { resource: services/branch.yml }
  - { resource: services/commit.yml }
  - { resource: services/user.yml }
  - { resource: services/webhook.yml }
services:

  github.event.handler:
    class: DevBoard\GithubEvent\EventHandler
    arguments:
      - @github.event.payload.factory
      - @github.event.push.branch.handler

  github.event.payload.factory:
    class: DevBoard\GithubEvent\Payload\PayloadFactory


  github.event.push.branch.data.repo.factory:
    class: DevBoard\GithubEvent\Push\Branch\Data\RepoFactory
  github.event.push.branch.data.branch.factory:
    class: DevBoard\GithubEvent\Push\Branch\Data\BranchFactory
  github.event.push.branch.data.commit.factory:
    class: DevBoard\GithubEvent\Push\Branch\Data\CommitFactory
  github.event.push.branch.data.commit_author.factory:
    class: DevBoard\GithubEvent\Push\Branch\Data\CommitAuthorFactory
  github.event.push.branch.data.commit_committer.factory:
    class: DevBoard\GithubEvent\Push\Branch\Data\CommitCommitterFactory



  github.event.push.branch.handler:
    class: DevBoard\GithubEvent\Push\Branch\BranchHandler
    arguments:
      - @github.event.push.branch.data.repo.factory
      - @github.event.push.branch.data.branch.factory
      - @github.event.push.branch.data.commit.factory
      - @github.event.push.branch.data.commit_author.factory
      - @github.event.push.branch.data.commit_committer.factory
      - @github.repo.facade
      - @github.branch.facade
      - @github.commit.facade
      - @github.user.facade
      - @doctrine.orm.entity_manager

  github.event.push.tag.handler:
    class: DevBoard\GithubEvent\Push\Tag\TagHandler

  github.event.push.handler:
    class: DevBoard\GithubEvent\Push\PushHandler
    arguments:
      - @github.event.push.branch.handler
      - @github.event.push.tag.handler