imports:
  - { resource: services/repo.yml }
  - { resource: services/branch.yml }
  - { resource: services/commit.yml }
  - { resource: services/commitstatus.yml }
  - { resource: services/pull_request.yml }
  - { resource: services/tag.yml }
  - { resource: services/user.yml }
  - { resource: services/externalservices.yml }
  - { resource: services/webhook.yml }
  - { resource: services/event/main.yml }
  - { resource: services/remote.yml }
  - { resource: services/sync.yml }
services:
