services:
  github.branch.repository:
    class: Doctrine\ORM\EntityRepository
    factory_service: doctrine.orm.default_entity_manager
    factory_method: getRepository
    arguments:
      - DevBoard\Github\Branch\Entity\GithubBranch

  github.branch.factory:
    class: DevBoard\Github\Branch\Entity\GithubBranchFactory
    arguments:
      - @github.branch.mapper.remote_to_entity

  github.branch.mapper.remote_to_entity:
    class: DevBoard\Github\Branch\Mapper\RemoteToEntityMapper

  github.branch.facade:
    class: DevBoard\Github\Branch\GithubBranchFacade
    arguments:
      - @github.branch.repository
      - @github.branch.factory
      - @doctrine.orm.entity_manager