services:
  github.commit.repository:
    class: Doctrine\ORM\EntityRepository
    factory_service: doctrine.orm.default_entity_manager
    factory_method: getRepository
    arguments:
      - DevBoard\Github\Commit\Entity\GithubCommit
      
  github.commit.factory:
    class: DevBoard\Github\Commit\Entity\GithubCommitFactory
    arguments:
      - @github.commit.mapper.remote_to_entity
      
  github.commit.mapper.remote_to_entity:
    class: DevBoard\Github\Commit\Mapper\RemoteToEntityMapper
    
  github.commit.facade:
    class: DevBoard\Github\Commit\GithubCommitFacade
    arguments:
      - @github.commit.repository
      - @github.commit.factory
      - @doctrine.orm.entity_manager