services:
  github.commitstatus.repository:
    class: Doctrine\ORM\EntityRepository
    factory_service: doctrine.orm.default_entity_manager
    factory_method: getRepository
    arguments:
      - DevBoard\Github\CommitStatus\Entity\GithubCommitStatus
      
  github.commitstatus.factory:
    class: DevBoard\Github\CommitStatus\Entity\GithubCommitStatusFactory
    arguments:
      - @github.commitstatus.mapper.remote_to_entity
      
  github.commitstatus.mapper.remote_to_entity:
    class: DevBoard\Github\CommitStatus\Mapper\RemoteToEntityMapper
    
  github.commitstatus.facade:
    class: DevBoard\Github\CommitStatus\GithubCommitStatusFacade
    arguments:
      - @github.commitstatus.repository
      - @github.commitstatus.factory
      - @doctrine.orm.entity_manager