services:
  github.externalservices.repository:
    class: Doctrine\ORM\EntityRepository
    factory_service: doctrine.orm.default_entity_manager
    factory_method: getRepository
    arguments:
      - DevBoard\Github\ExternalService\Entity\GithubExternalService
      
  github.externalservices.factory:
    class: DevBoard\Github\ExternalService\Entity\GithubExternalServiceFactory
    arguments:
      - @github.externalservices.mapper.remote_to_entity
      
  github.externalservices.mapper.remote_to_entity:
    class: DevBoard\Github\ExternalService\Mapper\RemoteToEntityMapper
    
  github.externalservices.facade:
    class: DevBoard\Github\ExternalService\GithubExternalServiceFacade
    arguments:
      - @github.externalservices.repository
      - @github.externalservices.factory
      - @doctrine.orm.entity_manager