imports:
  - { resource: services/api/branch.yml }
  - { resource: services/api/commit.yml }
  - { resource: services/api/repo.yml }
  - { resource: services/api/tag.yml }
  - { resource: services/api/user.yml }

services:
  null_dev_github_api.client.authenticated.factory.token:
    class: NullDev\GithubApi\Client\Authenticated\TokenAuthenticatedClientFactory
