services:
#    null_dev_github_api.example:
#        class: NullDev\GithubApiBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    null_dev_github_api.client.authenticated.factory.token:
        class: NullDev\GithubApi\Client\Authenticated\TokenAuthenticatedClientFactory

    null_dev_github_api.repo.data.factory:
        class: NullDev\GithubApi\Repo\GithubRepoDataFactory

    null_dev_github_api.repo.service:
        class: NullDev\GithubApi\Repo\RemoteGithubRepoService
        arguments:
          - @null_dev_github_api.client.authenticated.factory.token
          - @null_dev_github_api.repo.data.factory


    null_dev_github_api.user.data.factory:
        class: NullDev\GithubApi\User\GithubUserDataFactory

    null_dev_github_api.user.service:
        class: NullDev\GithubApi\User\RemoteGithubUserService
        arguments:
          - @null_dev_github_api.client.authenticated.factory.token
          - @null_dev_github_api.user.data.factory
